# permissions for end users to edit loxilights.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loxilight-editor-role
rules:
- apiGroups:
  - netlox.netlox.io
  resources:
  - loxilights
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - netlox.netlox.io
  resources:
  - loxilights/status
  verbs:
  - get
