# permissions for end users to view loxilightds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loxilightd-viewer-role
rules:
- apiGroups:
  - cache.netlox.io
  resources:
  - loxilightds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.netlox.io
  resources:
  - loxilightds/status
  verbs:
  - get
