# permissions for end users to view loxilights.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loxilight-viewer-role
rules:
- apiGroups:
  - netlox.netlox.io
  resources:
  - loxilights
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - netlox.netlox.io
  resources:
  - loxilights/status
  verbs:
  - get
