# permissions for end users to edit loxilightds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loxilightd-editor-role
rules:
- apiGroups:
  - cache.netlox.io
  resources:
  - loxilightds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.netlox.io
  resources:
  - loxilightds/status
  verbs:
  - get
