---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - netlox.netlox.io
  resources:
  - loxilights
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - netlox.netlox.io
  resources:
  - loxilights/finalizers
  verbs:
  - update
- apiGroups:
  - netlox.netlox.io
  resources:
  - loxilights/status
  verbs:
  - get
  - patch
  - update
